### ISSUE TITLE
Load balancer in case of multiple nodes.

### ISSUE THREAD

**Issue by blmhemu** [mr-karan/hydra#11]
Hey ! I see that you are using a single node setup and there is no need of a LB. I cannot help but ask, if there are multiple nodes (say 3), then how would caddy or any reverse proxy work (Installing on all nodes would be an option. But then to which node will you call for a service)? For k3s, I see metallb as a good option as it does some arp/bgp magic so that requests are forwarded to healthy nodes without an external load balancer. But in the case of nomad / consul, I cannot see how I can get away without an external LB.

**Comment by pratikbalar** [comment]
Now that you said, im also wondering how to LB in Nomad

**Comment by blmhemu** [comment]
I have been researching this topic for close to a week without concrete answers ...
But here are my 2 cents : Nomad does not seem to have an metalLB alternative (at least officially). I have seen that in many tutorials, hashicorp recommends we use an external VM with consul and nginx/haproxy installed and use it as lb.

**Comment by mr-karan** [comment]
Ah yes, Nomad doesn't have a Metal LB like offering simply because it doesn't have `kube-svc` or a similar service to manage networking. (There is consul-connect, however that is a service mesh used for internal communication within the cluster).

To use an external Load Balancer, I think you can:

- If on AWS, use ALB and set target group to Nomad agents where NGINX/HAProxy/Fabio is running. You can run these as a `System` job(https://www.nomadproject.io/docs/schedulers#system) which basically ensures it's running in all nodes.
- Otherwise, you can simply expose NGINX/HAProxy within your cluster on a public network interface. I'm actually doing this (https://github.com/mr-karan/hydra/blob/master/terraform/modules/caddy/conf/caddy.nomad#L21), where I am running 2 instances of Caddy on different network interfaces (Tailscale and Public).

So it doesn't matter, if it's one node or multiple. Only thing that now you need to orchestrate and manage is that if you've multiple public IPs for multiple NGINX, you need to configure your DNS to add all the endpoints to the record.

**Comment by blmhemu** [comment]
I found some tips here: https://learn.hashicorp.com/tutorials/nomad/load-balancing

But I cannot understand this https://learn.hashicorp.com/tutorials/nomad/load-balancing#use-service-scheduler-with-1-instances-of-your-load-balancer

![image](https://user-images.githubusercontent.com/19410501/120324191-f9e84880-c303-11eb-84a4-d0e135bdd45d.png)

**Comment by blmhemu** [comment]
Also adding to what @mr-karan said, I also think (this is purely my imagination, correct me if wrong), we can probably use DNS to "kinda" load balance.
Here is a clear explanation:
1. Setup consul DNS on all nodes
2. Setup all the nodes as DNS servers (expose dns port)
3. In the DNS server of the router (if the router can accommodate multiple DNS servers), add all the nodes as the dns servers.
4. The assumption is that when we get a request on say *.consul, these will first be looked up in nodes and unhealthy nodes will be skipped.
