### ISSUE TITLE
Storage on RPI4 ?

### ISSUE THREAD

**Issue by azr** [mr-karan/hydra#4]
Hello there, I was reading your recent [blog post](https://mrkaran.dev/posts/home-server-nomad/) and was wondering what you were using for storage ? Are you storing things directly in DO ? Or in the RPI4s ?

In general I'm also curious about your hardware setup too. I'd like to start like a home lab but there are so many choices.

PS: awesome blog post ! Thanks !

**Comment by mr-karan** [comment]
Thanks for your kind words.

I was previously using a mix set of H/W (RPis to run stateless workloads and DO Droplet for persistent). There's actually [Longhorn](https://longhorn.io/) that you can try for storing (I was using k3s at this point but I couldn't get to try it since it didn't have arm64 support back then).

I've moved away from this setup and only hosting my workloads on DO droplet. I use their block storage for it and take periodic backups with Restic! 

> I'm also curious about your hardware setup too.

I don't run any H/W at home, besides the RPi 4GB and RPi 2GB :) That's more than enough for my setup!

Cheers.

**Comment by azr** [comment]
Thanks, all questions answered ! I think this is smart because it's simple 👍🏼 .
